"""Typing surface for the native extension."""

import numpy as np
from numpy.typing import NDArray

class BatchSimulator:
    """Native independent-world simulator."""

    def __init__(self, config_json: str, state_json: str, num_worlds: int) -> None: ...
    @property
    def num_worlds(self) -> int: ...
    @staticmethod
    def state_width() -> int: ...
    def reset(self) -> NDArray[np.float32]: ...
    def step(self, actions: NDArray[np.float32]) -> NDArray[np.float32]: ...
    def snapshots(self) -> list[str]: ...
    def restore(self, index: int, snapshot_json: str) -> None: ...
